const eventsNear = [
    {   
        image: "../assets/images/events-near/1.jpg",
        title: "Day Trading Idea and Strategy",
        topic: "Business",
        distance: "(5 km)",
        data: "Mon, Mar 18 · 7:00 PM PDT",
        attendee: 1,
        price: "Free",
        online: false,
    },
    {   
        image: "../assets/images/events-near/2.jpg",
        title: "Let's Talk Networking: JPMorgan Chase in Palo Alto",
        topic: "Business",
        distance: "(25 km)",
        data: "Tue, Mar 19 · 5:00 PM PDT",
        attendee: 41,
        price: "Free",
        online: false,
    },
    {   
        image: "../assets/images/events-near/3.jpg",
        title: "Tech Talks & Quiz: Next-Gen Database Solutions for Emerging Use Cases",
        topic: "Technology",
        distance: "",
        data: "Wed, Mar 13 · 6:00 PM PDT",
        attendee: 40,
        price: "Free",
        online: true,
    },
    {   
        image: "../assets/images/events-near/4.jpg",
        title: "INFORMS San Francisco Chapter In-Person Event",
        topic: "Health and Wellbeing",
        distance: "(50 km)",
        data: "Thu, Mar 28 · 5:00 PM PDT",
        attendee: 41,
        price: "Free",
        online: false,
    },
    {   
        image: "../assets/images/events-near/5.jpg",
        title: "AI Wednesdays - Meet and Greet!",
        topic: "Technology",
        distance: "(5 km)",
        data: "Wed, Mar 13 · 6:30 PM PDT",
        attendee: 29,
        price: "Free",
        online: false,
    },
    {   
        image: "../assets/images/events-near/6.jpg",
        title: "ROS By-The-Bay March 2024",
        topic: "Social Activities",
        distance: "",
        data: "Thu, Mar 21 · 6:00 PM PDT",
        attendee: 51,
        price: "Free",
        online: true,
    },
    {   
        image: "../assets/images/events-near/7.jpg",
        title: "Free Christian Singles' Dinner",
        topic: "Hobbies and Passions",
        distance: "(10 km)",
        data: "Fri, Mar 29 · 6:00 PM PDT",
        attendee: 11,
        price: "Free",
        online: false,
    },
    {   
        image: "../assets/images/events-near/8.jpg",
        title: "In-person: Deep Dive into RAG Architectures (Food served)",
        topic: "Hobbies and Passions",
        distance: "(50 km)",
        data: "Thu, Mar 14 · 5:00 PM PDT",
        attendee: 16,
        price: "Free",
        online: false,
    },
]